"""Agregar Columna

Revision ID: 8efcb7bafe67
Revises: 
Create Date: 2023-03-13 18:08:23.454969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8efcb7bafe67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username_id', sa.Integer(), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('descripcion_productos', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['username_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ventas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ventas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('venta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ventas_productos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['username_id'], ['usuario.id'], name='ventas_username_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ventas_pkey')
    )
    op.drop_table('productos')
    # ### end Alembic commands ###
